import type {
  Animal,
  Region,
  DonationTier,
  MembershipTier,
  ShopItem,
  NavLink,
  ImpactStat,
  BlogPost,
} from '@/types'

export const NAV_LINKS: NavLink[] = [
  { label: 'Animals', href: '/animals' },
  { label: 'Regions', href: '/regions' },
  { label: 'Blog', href: '/blog' },
  { label: 'Shop', href: '/shop' },
  { label: 'About', href: '/about' },
]

export const IMPACT_STATS: ImpactStat[] = [
  { value: '1,200+', label: 'Animals Protected', icon: 'shield' },
  { value: '850K', label: 'Hectares Conserved', icon: 'trees' },
  { value: '42', label: 'Partner Countries', icon: 'globe' },
  { value: '18K+', label: 'Community Members', icon: 'users' },
]

export const ANIMALS: Animal[] = [
  {
    slug: 'african-elephant',
    name: 'African Elephant',
    species: 'Loxodonta africana',
    commonName: 'African Bush Elephant',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Botswana', 'Zimbabwe', 'Zambia'],
    conservationStatus: 'Vulnerable',
    population: { current: 415000, trend: 'Decreasing', year: 2023 },
    habitat: ['Savannah', 'Forest', 'Desert', 'Wetlands'],
    description:
      'The African elephant is the largest land animal on Earth. These magnificent creatures play a crucial role in maintaining the ecosystems they inhabit, creating waterholes used by other animals and dispersing seeds across vast distances.',
    imageUrl:
      'https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=400&q=80',
    facts: [
      { label: 'Weight', value: 'Up to 6,000 kg' },
      { label: 'Lifespan', value: '60–70 years' },
      { label: 'Gestation', value: '22 months' },
      { label: 'Trunk muscles', value: '40,000+' },
    ],
    adoptionTiers: [
      { id: 'elephant-basic', animalSlug: 'african-elephant', label: 'Calf Sponsor', amount: 15, interval: 'month', description: 'Support a young elephant', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'elephant-pro', animalSlug: 'african-elephant', label: 'Herd Guardian', amount: 35, interval: 'month', description: 'Protect an entire family', perks: ['Digital certificate', 'Monthly update', 'Printed photo', 'Name on donor wall'] },
    ],
    fundingGoal: 60000,
    fundingRaised: 28450,
  },
  {
    slug: 'mountain-gorilla',
    name: 'Mountain Gorilla',
    species: 'Gorilla beringei beringei',
    commonName: 'Mountain Gorilla',
    region: 'Central Africa',
    countries: ['Uganda', 'Rwanda', 'DR Congo'],
    conservationStatus: 'Endangered',
    population: { current: 1063, trend: 'Increasing', year: 2023 },
    habitat: ['Montane Forest', 'Bamboo Forest'],
    description:
      'One of our closest living relatives, mountain gorillas live in the high-altitude forests of the Virunga mountains. Conservation efforts have helped their population slowly recover from near extinction.',
    imageUrl:
      'https://images.unsplash.com/photo-1605552329467-0e5f3c1d7b3a?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1605552329467-0e5f3c1d7b3a?w=400&q=80',
    facts: [
      { label: 'Weight', value: '135–180 kg (male)' },
      { label: 'Lifespan', value: '35–40 years' },
      { label: 'Group size', value: '5–30 individuals' },
      { label: 'DNA similarity', value: '98.3% with humans' },
    ],
    adoptionTiers: [
      { id: 'gorilla-basic', animalSlug: 'mountain-gorilla', label: 'Troop Friend', amount: 20, interval: 'month', description: 'Help protect a gorilla family', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'gorilla-pro', animalSlug: 'mountain-gorilla', label: 'Silverback Ally', amount: 45, interval: 'month', description: 'Fully sponsor a gorilla group', perks: ['All Troop Friend perks', 'Printed photo', 'Ranger update letter'] },
    ],
    fundingGoal: 45000,
    fundingRaised: 31200,
  },
  {
    slug: 'african-lion',
    name: 'African Lion',
    species: 'Panthera leo',
    commonName: 'African Lion',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'South Africa', 'Botswana', 'Zimbabwe'],
    conservationStatus: 'Vulnerable',
    population: { current: 23000, trend: 'Decreasing', year: 2023 },
    habitat: ['Savannah', 'Grassland', 'Open Woodland'],
    description:
      'The king of the savannah, African lions are the only truly social wild cats. They live in prides and are apex predators critical to maintaining healthy ecosystems. Their populations have declined by 43% in the last two decades.',
    imageUrl:
      'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=400&q=80',
    facts: [
      { label: 'Weight', value: '150–250 kg' },
      { label: 'Lifespan', value: '10–14 years' },
      { label: 'Roar range', value: '8 km' },
      { label: 'Pride size', value: 'Up to 30 lions' },
    ],
    adoptionTiers: [
      { id: 'lion-basic', animalSlug: 'african-lion', label: 'Pride Supporter', amount: 18, interval: 'month', description: 'Help protect a lion pride', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'lion-pro', animalSlug: 'african-lion', label: 'Mane Guardian', amount: 40, interval: 'month', description: 'Sponsor anti-poaching patrols for lions', perks: ['All Pride Supporter perks', 'GPS tracker update', 'Name on pride plaque'] },
    ],
    fundingGoal: 50000,
    fundingRaised: 19800,
  },
  {
    slug: 'black-rhino',
    name: 'Black Rhino',
    species: 'Diceros bicornis',
    commonName: 'Black Rhinoceros',
    region: 'Southern Africa',
    countries: ['South Africa', 'Namibia', 'Zimbabwe', 'Kenya'],
    conservationStatus: 'Critically Endangered',
    population: { current: 6195, trend: 'Increasing', year: 2023 },
    habitat: ['Savannah', 'Bushland', 'Desert'],
    description:
      'Once widespread across sub-Saharan Africa, black rhinos were driven to near extinction by poaching for their horns. Intensive conservation efforts have allowed their numbers to slowly recover, but they remain critically endangered.',
    imageUrl:
      'https://images.unsplash.com/photo-1598885159317-6c7f752e4f61?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1598885159317-6c7f752e4f61?w=400&q=80',
    facts: [
      { label: 'Weight', value: '800–1,400 kg' },
      { label: 'Horn growth', value: '2.5–5 cm/year' },
      { label: 'Lifespan', value: '35–50 years' },
      { label: 'Speed', value: 'Up to 55 km/h' },
    ],
    adoptionTiers: [
      { id: 'rhino-basic', animalSlug: 'black-rhino', label: 'Horn Protector', amount: 25, interval: 'month', description: 'Help fund anti-poaching units', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'rhino-pro', animalSlug: 'black-rhino', label: 'Rhino Ranger', amount: 60, interval: 'month', description: 'Full sponsorship of a rhino patrol unit', perks: ['All protector perks', 'Field report', 'Ranger field call'] },
    ],
    fundingGoal: 75000,
    fundingRaised: 42100,
  },
  {
    slug: 'cheetah',
    name: 'Cheetah',
    species: 'Acinonyx jubatus',
    commonName: 'Cheetah',
    region: 'East Africa',
    countries: ['Tanzania', 'Kenya', 'Namibia', 'Botswana'],
    conservationStatus: 'Vulnerable',
    population: { current: 7100, trend: 'Decreasing', year: 2023 },
    habitat: ['Savannah', 'Grassland', 'Semi-arid'],
    description:
      'The world\'s fastest land animal, the cheetah has lost 91% of its historic range. Habitat loss, conflict with farmers, and illegal wildlife trade threaten their survival across Africa.',
    imageUrl:
      'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=400&q=80',
    facts: [
      { label: 'Top speed', value: '112 km/h' },
      { label: 'Acceleration', value: '0–96 km/h in 3s' },
      { label: 'Lifespan', value: '10–12 years' },
      { label: 'Cubs per litter', value: '3–5' },
    ],
    adoptionTiers: [
      { id: 'cheetah-basic', animalSlug: 'cheetah', label: 'Sprint Sponsor', amount: 15, interval: 'month', description: 'Support a cheetah family', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'cheetah-pro', animalSlug: 'cheetah', label: 'Speed Champion', amount: 35, interval: 'month', description: 'Full habitat corridor sponsorship', perks: ['All Sprint Sponsor perks', 'GPS collar update', 'Photo print'] },
    ],
    fundingGoal: 40000,
    fundingRaised: 15600,
  },
  {
    slug: 'african-wild-dog',
    name: 'African Wild Dog',
    species: 'Lycaon pictus',
    commonName: 'Painted Wolf',
    region: 'Southern Africa',
    countries: ['Zimbabwe', 'Botswana', 'Tanzania', 'Mozambique'],
    conservationStatus: 'Endangered',
    population: { current: 6600, trend: 'Decreasing', year: 2023 },
    habitat: ['Savannah', 'Woodland', 'Grassland'],
    description:
      'African wild dogs are among the most successful hunters on the continent, with a hunting success rate of 80%. They are highly social and caring animals, but face threats from habitat fragmentation and disease.',
    imageUrl:
      'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=400&q=80',
    facts: [
      { label: 'Pack size', value: '10–40 members' },
      { label: 'Hunt success', value: '80%' },
      { label: 'Speed', value: 'Up to 66 km/h' },
      { label: 'Lifespan', value: '10–12 years' },
    ],
    adoptionTiers: [
      { id: 'wilddog-basic', animalSlug: 'african-wild-dog', label: 'Pack Ally', amount: 15, interval: 'month', description: 'Support a wild dog pack', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'wilddog-pro', animalSlug: 'african-wild-dog', label: 'Alpha Supporter', amount: 35, interval: 'month', description: 'Sponsor full pack habitat protection', perks: ['All Pack Ally perks', 'Pack tracking update', 'Photo print'] },
    ],
    fundingGoal: 35000,
    fundingRaised: 12300,
  },
  {
    slug: 'pangolin',
    name: 'Ground Pangolin',
    species: 'Smutsia temminckii',
    commonName: 'Temminck\'s Ground Pangolin',
    region: 'Southern Africa',
    countries: ['South Africa', 'Zimbabwe', 'Botswana', 'Kenya'],
    conservationStatus: 'Vulnerable',
    population: { current: null, trend: 'Decreasing', year: 2023 },
    habitat: ['Savannah', 'Woodland', 'Grassland'],
    description:
      'Pangolins are the world\'s most trafficked mammals. Their unique scales, made of keratin, make them targets for illegal wildlife trade. They are vital ecosystem engineers, consuming millions of insects annually.',
    imageUrl:
      'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400&q=80',
    facts: [
      { label: 'Scales', value: 'Made of keratin' },
      { label: 'Diet', value: '70M insects/year' },
      { label: 'Defense', value: 'Roll into a ball' },
      { label: 'Tongue length', value: 'Longer than body' },
    ],
    adoptionTiers: [
      { id: 'pangolin-basic', animalSlug: 'pangolin', label: 'Scale Shield', amount: 12, interval: 'month', description: 'Help fight pangolin trafficking', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'pangolin-pro', animalSlug: 'pangolin', label: 'Pangolin Protector', amount: 30, interval: 'month', description: 'Sponsor anti-trafficking operations', perks: ['All Scale Shield perks', 'Rescue operation update', 'Photo print'] },
    ],
    fundingGoal: 30000,
    fundingRaised: 9800,
  },
  {
    slug: 'hippopotamus',
    name: 'Hippopotamus',
    species: 'Hippopotamus amphibius',
    commonName: 'Common Hippo',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Uganda', 'Zambia', 'DR Congo'],
    conservationStatus: 'Vulnerable',
    population: { current: 115000, trend: 'Decreasing', year: 2023 },
    habitat: ['Rivers', 'Lakes', 'Wetlands'],
    description:
      'Hippos are among Africa\'s most dangerous animals and critical ecosystem engineers. They fertilize rivers and lakes with their dung, supporting vast aquatic food chains. Habitat loss and poaching threaten their survival.',
    imageUrl:
      'https://images.unsplash.com/photo-1578153309-ecca47d37985?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1578153309-ecca47d37985?w=400&q=80',
    facts: [
      { label: 'Weight', value: '1,500–3,200 kg' },
      { label: 'Swim speed', value: '8 km/h' },
      { label: 'Underwater', value: 'Up to 5 minutes' },
      { label: 'Lifespan', value: '40–50 years' },
    ],
    adoptionTiers: [
      { id: 'hippo-basic', animalSlug: 'hippopotamus', label: 'River Guardian', amount: 15, interval: 'month', description: 'Protect hippo river habitats', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'hippo-pro', animalSlug: 'hippopotamus', label: 'Wetland Champion', amount: 35, interval: 'month', description: 'Full wetland habitat sponsorship', perks: ['All River Guardian perks', 'Habitat report', 'Photo print'] },
    ],
    fundingGoal: 38000,
    fundingRaised: 14200,
  },
  {
    slug: 'african-penguin',
    name: 'African Penguin',
    species: 'Spheniscus demersus',
    commonName: 'African Penguin',
    region: 'Southern Africa',
    countries: ['South Africa', 'Namibia'],
    conservationStatus: 'Endangered',
    population: { current: 50000, trend: 'Decreasing', year: 2023 },
    habitat: ['Coastal', 'Marine', 'Rocky Islands'],
    description:
      'The only penguin species found in Africa, the African penguin breeds on the southwestern coast. Their population has collapsed by over 70% in 30 years due to overfishing, oil spills, and climate change.',
    imageUrl:
      'https://images.unsplash.com/photo-1598153346810-860daa814c4b?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1598153346810-860daa814c4b?w=400&q=80',
    facts: [
      { label: 'Height', value: '60–70 cm' },
      { label: 'Swim speed', value: 'Up to 20 km/h' },
      { label: 'Lifespan', value: '10–27 years' },
      { label: 'Call', value: 'Donkey-like bray' },
    ],
    adoptionTiers: [
      { id: 'penguin-basic', animalSlug: 'african-penguin', label: 'Colony Friend', amount: 12, interval: 'month', description: 'Support African penguin colonies', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'penguin-pro', animalSlug: 'african-penguin', label: 'Flipper Champion', amount: 28, interval: 'month', description: 'Full colony habitat protection', perks: ['All Colony Friend perks', 'Nest cam access', 'Photo print'] },
    ],
    fundingGoal: 28000,
    fundingRaised: 16900,
  },
  {
    slug: 'ethiopian-wolf',
    name: 'Ethiopian Wolf',
    species: 'Canis simensis',
    commonName: 'Ethiopian Wolf',
    region: 'East Africa',
    countries: ['Ethiopia'],
    conservationStatus: 'Endangered',
    population: { current: 500, trend: 'Stable', year: 2023 },
    habitat: ['Afroalpine Moorland', 'Highland Grassland'],
    description:
      'The Ethiopian wolf is the world\'s rarest canid and Africa\'s most endangered carnivore. Found only in the Ethiopian highlands, they are specialized hunters of Afroalpine rodents. Disease and habitat loss are their greatest threats.',
    imageUrl:
      'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=400&q=80',
    facts: [
      { label: 'Population', value: '~500 adults' },
      { label: 'Range', value: 'Ethiopian highlands only' },
      { label: 'Diet', value: '95% Afroalpine rodents' },
      { label: 'Lifespan', value: '8–10 years' },
    ],
    adoptionTiers: [
      { id: 'wolf-basic', animalSlug: 'ethiopian-wolf', label: 'Highlands Ally', amount: 18, interval: 'month', description: 'Help save the rarest wolf', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'wolf-pro', animalSlug: 'ethiopian-wolf', label: 'Pack Defender', amount: 40, interval: 'month', description: 'Sponsor disease vaccination program', perks: ['All Highlands Ally perks', 'Vaccination report', 'Photo print'] },
    ],
    fundingGoal: 25000,
    fundingRaised: 11700,
  },
  {
    slug: 'okapi',
    name: 'Okapi',
    species: 'Okapia johnstoni',
    commonName: 'Okapi',
    region: 'Central Africa',
    countries: ['DR Congo'],
    conservationStatus: 'Endangered',
    population: { current: 35000, trend: 'Decreasing', year: 2023 },
    habitat: ['Tropical Rainforest'],
    description:
      'Often called the "forest giraffe," the okapi is a shy, solitary mammal found only in the Ituri Rainforest of DR Congo. Related to giraffes, they are elusive and poorly understood, threatened by deforestation and poaching.',
    imageUrl:
      'https://images.unsplash.com/photo-1504450874802-0ba2bcd9b5ae?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1504450874802-0ba2bcd9b5ae?w=400&q=80',
    facts: [
      { label: 'Tongue length', value: '30–36 cm' },
      { label: 'Relative', value: 'Giraffe family' },
      { label: 'Habitat', value: 'Ituri Forest, DR Congo' },
      { label: 'Lifespan', value: '20–30 years' },
    ],
    adoptionTiers: [
      { id: 'okapi-basic', animalSlug: 'okapi', label: 'Forest Friend', amount: 15, interval: 'month', description: 'Protect okapi rainforest habitat', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'okapi-pro', animalSlug: 'okapi', label: 'Ituri Guardian', amount: 35, interval: 'month', description: 'Full forest patrol sponsorship', perks: ['All Forest Friend perks', 'Forest report', 'Photo print'] },
    ],
    fundingGoal: 32000,
    fundingRaised: 8400,
  },
  {
    slug: 'grevy-zebra',
    name: "Grévy's Zebra",
    species: "Equus grevyi",
    commonName: "Grévy's Zebra",
    region: 'East Africa',
    countries: ['Kenya', 'Ethiopia'],
    conservationStatus: 'Endangered',
    population: { current: 2800, trend: 'Stable', year: 2023 },
    habitat: ['Semi-arid Grassland', 'Thornbush Savannah'],
    description:
      "The largest wild equid and most threatened zebra species, Grévy's zebra has the narrowest stripes of any zebra. Their population has declined dramatically due to competition with livestock and loss of water sources.",
    imageUrl:
      'https://images.unsplash.com/photo-1551316679-9c6ae9dec224?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1551316679-9c6ae9dec224?w=400&q=80',
    facts: [
      { label: 'Weight', value: '350–450 kg' },
      { label: 'Stripe pattern', value: 'Unique to each individual' },
      { label: 'Lifespan', value: '25–30 years' },
      { label: 'Social structure', value: 'Non-territorial herds' },
    ],
    adoptionTiers: [
      { id: 'grevy-basic', animalSlug: 'grevy-zebra', label: 'Stripe Sponsor', amount: 15, interval: 'month', description: 'Support Grévy\'s zebra conservation', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'grevy-pro', animalSlug: 'grevy-zebra', label: 'Plains Protector', amount: 35, interval: 'month', description: 'Water source protection program', perks: ['All Stripe Sponsor perks', 'Herd tracking update', 'Photo print'] },
    ],
    fundingGoal: 22000,
    fundingRaised: 7600,
  },
  {
    slug: 'nile-crocodile',
    name: 'Nile Crocodile',
    species: 'Crocodylus niloticus',
    commonName: 'Nile Crocodile',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Egypt', 'Uganda', 'Zambia'],
    conservationStatus: 'Least Concern',
    population: { current: 250000, trend: 'Stable', year: 2023 },
    habitat: ['Rivers', 'Lakes', 'Wetlands'],
    description:
      'The Nile crocodile is Africa\'s largest freshwater predator and a keystone species. As apex predators, they regulate prey populations and their basking maintains open riverbanks used by many other species.',
    imageUrl:
      'https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0?w=400&q=80',
    facts: [
      { label: 'Length', value: 'Up to 6 m' },
      { label: 'Weight', value: 'Up to 730 kg' },
      { label: 'Lifespan', value: '70–100 years' },
      { label: 'Bite force', value: 'Strongest of any animal' },
    ],
    adoptionTiers: [
      { id: 'croc-basic', animalSlug: 'nile-crocodile', label: 'River Ally', amount: 10, interval: 'month', description: 'Protect crocodile river habitats', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'croc-pro', animalSlug: 'nile-crocodile', label: 'Apex Defender', amount: 25, interval: 'month', description: 'Wetland ecosystem protection', perks: ['All River Ally perks', 'Habitat report', 'Photo print'] },
    ],
    fundingGoal: 20000,
    fundingRaised: 6300,
  },
  {
    slug: 'african-leopard',
    name: 'African Leopard',
    species: 'Panthera pardus pardus',
    commonName: 'African Leopard',
    region: 'Southern Africa',
    countries: ['South Africa', 'Kenya', 'Tanzania', 'Zambia', 'Zimbabwe'],
    conservationStatus: 'Vulnerable',
    population: { current: 70000, trend: 'Decreasing', year: 2023 },
    habitat: ['Savannah', 'Forest', 'Mountains', 'Desert'],
    description:
      'The most widespread of Africa\'s big cats, leopards are masters of stealth and adaptability. They are solitary and nocturnal, hauling prey up trees to protect it from lions and hyenas. Habitat loss and conflict with farmers are major threats.',
    imageUrl:
      'https://images.unsplash.com/photo-1512236258305-32fb110fdb01?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1512236258305-32fb110fdb01?w=400&q=80',
    facts: [
      { label: 'Weight', value: '30–90 kg' },
      { label: 'Lifespan', value: '12–17 years' },
      { label: 'Tree-climbing', value: 'Can carry 3× their weight' },
      { label: 'Speed', value: 'Up to 58 km/h' },
    ],
    adoptionTiers: [
      { id: 'leopard-basic', animalSlug: 'african-leopard', label: 'Shadow Sponsor', amount: 18, interval: 'month', description: 'Support leopard habitat protection', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'leopard-pro', animalSlug: 'african-leopard', label: 'Spot Guardian', amount: 40, interval: 'month', description: 'Anti-poaching patrol sponsorship', perks: ['All Shadow Sponsor perks', 'Camera trap images', 'Photo print'] },
    ],
    fundingGoal: 42000,
    fundingRaised: 17500,
  },
  {
    slug: 'white-rhino',
    name: 'White Rhino',
    species: 'Ceratotherium simum',
    commonName: 'White Rhinoceros',
    region: 'Southern Africa',
    countries: ['South Africa', 'Kenya', 'Zimbabwe', 'Botswana'],
    conservationStatus: 'Near Threatened',
    population: { current: 17212, trend: 'Stable', year: 2023 },
    habitat: ['Grassland', 'Savannah', 'Bushland'],
    description:
      'The largest of the five rhino species, the white rhino is a grazer that plays a vital role in maintaining grasslands. While southern white rhinos have recovered from near extinction, they remain targets for poaching.',
    imageUrl:
      'https://images.unsplash.com/photo-1508764493775-43e2441c8d15?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1508764493775-43e2441c8d15?w=400&q=80',
    facts: [
      { label: 'Weight', value: '1,800–2,700 kg' },
      { label: 'Horn material', value: 'Keratin (same as fingernails)' },
      { label: 'Lifespan', value: '40–50 years' },
      { label: 'Speed', value: 'Up to 50 km/h' },
    ],
    adoptionTiers: [
      { id: 'wrhino-basic', animalSlug: 'white-rhino', label: 'Grass Guardian', amount: 20, interval: 'month', description: 'Support white rhino conservation', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'wrhino-pro', animalSlug: 'white-rhino', label: 'Horn Protector', amount: 50, interval: 'month', description: 'Anti-poaching unit sponsorship', perks: ['All Grass Guardian perks', 'Ranger report', 'Photo print'] },
    ],
    fundingGoal: 40000,
    fundingRaised: 22100,
  },
  {
    slug: 'bonobo',
    name: 'Bonobo',
    species: 'Pan paniscus',
    commonName: 'Bonobo',
    region: 'Central Africa',
    countries: ['DR Congo'],
    conservationStatus: 'Endangered',
    population: { current: 15000, trend: 'Decreasing', year: 2023 },
    habitat: ['Tropical Rainforest'],
    description:
      'Bonobos are one of our two closest living relatives (with chimpanzees). Found only in DR Congo\'s rainforests, they are known for their peaceful, matriarchal social structures. Deforestation and bushmeat hunting threaten their survival.',
    imageUrl:
      'https://images.unsplash.com/photo-1577567583-7e7e5c0a1e7a?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1577567583-7e7e5c0a1e7a?w=400&q=80',
    facts: [
      { label: 'DNA similarity', value: '98.7% with humans' },
      { label: 'Social structure', value: 'Female-led' },
      { label: 'Lifespan', value: '40+ years' },
      { label: 'Range', value: 'Congo Basin only' },
    ],
    adoptionTiers: [
      { id: 'bonobo-basic', animalSlug: 'bonobo', label: 'Congo Ally', amount: 20, interval: 'month', description: 'Help protect bonobo forests', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'bonobo-pro', animalSlug: 'bonobo', label: 'Forest Keeper', amount: 45, interval: 'month', description: 'Full sanctuary sponsorship', perks: ['All Congo Ally perks', 'Sanctuary update', 'Photo print'] },
    ],
    fundingGoal: 35000,
    fundingRaised: 13900,
  },
  {
    slug: 'serval',
    name: 'Serval',
    species: 'Leptailurus serval',
    commonName: 'Serval',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Ethiopia', 'South Africa'],
    conservationStatus: 'Least Concern',
    population: { current: null, trend: 'Decreasing', year: 2023 },
    habitat: ['Wetlands', 'Savannah', 'Grassland'],
    description:
      'The serval is a slender wild cat with the longest legs and largest ears relative to body size of any cat. Highly skilled hunters, they rely on hearing to locate prey. Wetland drainage and illegal pet trade threaten their populations.',
    imageUrl:
      'https://images.unsplash.com/photo-1551975288-5e27e2a92c3d?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1551975288-5e27e2a92c3d?w=400&q=80',
    facts: [
      { label: 'Jump height', value: 'Up to 3.6 m vertical' },
      { label: 'Hearing range', value: 'High-frequency specialist' },
      { label: 'Lifespan', value: '10–12 years' },
      { label: 'Leg length', value: 'Longest relative to body of any cat' },
    ],
    adoptionTiers: [
      { id: 'serval-basic', animalSlug: 'serval', label: 'Long-Leg Ally', amount: 12, interval: 'month', description: 'Support serval wetland habitats', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'serval-pro', animalSlug: 'serval', label: 'Wetland Warden', amount: 28, interval: 'month', description: 'Wetland protection program', perks: ['All Long-Leg Ally perks', 'Habitat report', 'Photo print'] },
    ],
    fundingGoal: 18000,
    fundingRaised: 5200,
  },
  {
    slug: 'caracal',
    name: 'Caracal',
    species: 'Caracal caracal',
    commonName: 'Caracal',
    region: 'North Africa',
    countries: ['Morocco', 'Algeria', 'Sudan', 'Kenya', 'South Africa'],
    conservationStatus: 'Least Concern',
    population: { current: null, trend: 'Stable', year: 2023 },
    habitat: ['Semi-arid', 'Savannah', 'Woodland', 'Mountain'],
    description:
      'The caracal is a fierce and agile medium-sized wild cat, famous for its remarkable ability to leap and catch birds mid-flight. Its distinctive black ear tufts are iconic. Retaliatory killing by farmers is a major threat.',
    imageUrl:
      'https://images.unsplash.com/photo-1553535955-1e32ac67e567?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1553535955-1e32ac67e567?w=400&q=80',
    facts: [
      { label: 'Leap height', value: '3 m to catch birds' },
      { label: 'Ear tufts', value: '4.5 cm long' },
      { label: 'Speed', value: 'Up to 80 km/h in short bursts' },
      { label: 'Lifespan', value: '12–17 years' },
    ],
    adoptionTiers: [
      { id: 'caracal-basic', animalSlug: 'caracal', label: 'Ear Tuft Ally', amount: 12, interval: 'month', description: 'Support caracal coexistence programs', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'caracal-pro', animalSlug: 'caracal', label: 'Desert Guardian', amount: 28, interval: 'month', description: 'Livestock conflict resolution program', perks: ['All Ear Tuft Ally perks', 'Community report', 'Photo print'] },
    ],
    fundingGoal: 15000,
    fundingRaised: 4100,
  },
  {
    slug: 'african-wild-cat',
    name: 'African Wild Cat',
    species: 'Felis lybica',
    commonName: 'African Wild Cat',
    region: 'West Africa',
    countries: ['Nigeria', 'Ghana', 'Senegal', 'Mali', 'South Africa'],
    conservationStatus: 'Least Concern',
    population: { current: null, trend: 'Decreasing', year: 2023 },
    habitat: ['Savannah', 'Scrubland', 'Desert edge', 'Forest margin'],
    description:
      'The African wild cat is the ancestor of all domestic cats. Though widespread, they are threatened by interbreeding with domestic cats which dilutes their gene pool, and are an important part of rodent control in African ecosystems.',
    imageUrl:
      'https://images.unsplash.com/photo-1518715303843-586e350560d8?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1518715303843-586e350560d8?w=400&q=80',
    facts: [
      { label: 'Ancestor of', value: 'All domestic cats' },
      { label: 'Domesticated', value: '~10,000 years ago' },
      { label: 'Threat', value: 'Hybridization with domestic cats' },
      { label: 'Lifespan', value: '10–15 years' },
    ],
    adoptionTiers: [
      { id: 'wildcat-basic', animalSlug: 'african-wild-cat', label: 'Wild Ancestry Ally', amount: 10, interval: 'month', description: 'Protect wild cat genetic diversity', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'wildcat-pro', animalSlug: 'african-wild-cat', label: 'Gene Pool Guardian', amount: 22, interval: 'month', description: 'Hybridization prevention program', perks: ['All Ally perks', 'Research update', 'Photo print'] },
    ],
    fundingGoal: 12000,
    fundingRaised: 3600,
  },
  {
    slug: 'warthog',
    name: 'Warthog',
    species: 'Phacochoerus africanus',
    commonName: 'Common Warthog',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Uganda', 'Ethiopia', 'South Africa'],
    conservationStatus: 'Least Concern',
    population: { current: null, trend: 'Stable', year: 2023 },
    habitat: ['Savannah', 'Grassland', 'Woodland'],
    description:
      'Warthogs are tough, adaptable animals that play an important role in the savannah ecosystem. Their digging creates burrows used by many other species, and they are a key prey species for large predators.',
    imageUrl:
      'https://images.unsplash.com/photo-1590418606746-018840f9ffe0?w=1200&q=80',
    thumbnailUrl:
      'https://images.unsplash.com/photo-1590418606746-018840f9ffe0?w=400&q=80',
    facts: [
      { label: 'Tusks', value: 'Up to 60 cm long' },
      { label: 'Speed', value: 'Up to 48 km/h' },
      { label: 'Burrows', value: 'Used by many other species' },
      { label: 'Kneels', value: 'To graze on short grass' },
    ],
    adoptionTiers: [
      { id: 'warthog-basic', animalSlug: 'warthog', label: 'Tusk Ally', amount: 10, interval: 'month', description: 'Support savannah ecosystem health', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'warthog-pro', animalSlug: 'warthog', label: 'Savannah Steward', amount: 22, interval: 'month', description: 'Habitat corridor conservation', perks: ['All Tusk Ally perks', 'Ecosystem report', 'Photo print'] },
    ],
    fundingGoal: 10000,
    fundingRaised: 3100,
  },
  {
    slug: 'giraffe',
    name: 'Giraffe',
    species: 'Giraffa camelopardalis',
    commonName: 'Masai Giraffe',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Uganda', 'South Africa'],
    conservationStatus: 'Vulnerable',
    population: { current: 117000, trend: 'Decreasing', year: 2023 },
    habitat: ['Savannah', 'Open Woodland', 'Thornbush'],
    description:
      'The tallest animal on Earth, giraffes are iconic symbols of the African savannah. Their long necks allow them to browse leaves that other herbivores cannot reach, making them vital to their ecosystem. Silent extinction is a real risk — giraffe numbers have dropped 40% in 30 years.',
    extendedDescription:
      'Giraffes are highly social animals that live in loose herds called "towers." They have unique spot patterns, like human fingerprints, and sleep only 30 minutes a day in short naps. Their towering height — up to 5.5 metres — is both their greatest adaptation and a vulnerability: they must splay their legs to drink water, leaving them momentarily defenseless. Climate change is shrinking their acacia food sources across the Sahel.',
    imageUrl: 'https://images.unsplash.com/photo-1547721064-da6cfb341d50?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1547721064-da6cfb341d50?w=400&q=80',
    facts: [
      { label: 'Height', value: 'Up to 5.5 m' },
      { label: 'Tongue', value: '45–50 cm, dark blue' },
      { label: 'Heart', value: '11 kg, pumps up 2.5 m' },
      { label: 'Lifespan', value: '20–25 years' },
    ],
    threats: [
      { title: 'Habitat loss', description: 'Agricultural expansion and human settlement fragment giraffe corridors across East Africa.' },
      { title: 'Illegal hunting', description: 'Poaching for bush meat and tail hair tassels continues in several range states.' },
      { title: 'Climate change', description: 'Prolonged droughts reduce acacia availability, the giraffe\'s primary food source.' },
    ],
    ecoFacts: [
      { emoji: '🌿', label: 'Seed disperser', detail: 'Giraffes spread acacia seeds over vast distances through their digestive system, regenerating savannah woodland.' },
      { emoji: '🦅', label: 'Alarm system', detail: 'Their towering height gives them a wide field of vision, allowing them to detect predators and alert other species.' },
    ],
    adoptionTiers: [
      { id: 'giraffe-basic', animalSlug: 'giraffe', label: 'Neck Sponsor', amount: 15, interval: 'month', description: 'Support giraffe habitat protection', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'giraffe-pro', animalSlug: 'giraffe', label: 'Tower Guardian', amount: 35, interval: 'month', description: 'Fund corridor conservation programs', perks: ['All Neck Sponsor perks', 'GPS herd update', 'Photo print'] },
    ],
    fundingGoal: 45000,
    fundingRaised: 18200,
  },
  {
    slug: 'cape-buffalo',
    name: 'Cape Buffalo',
    species: 'Syncerus caffer',
    commonName: 'African Buffalo',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Uganda', 'Zambia', 'Zimbabwe', 'South Africa'],
    conservationStatus: 'Least Concern',
    population: { current: 900000, trend: 'Decreasing', year: 2023 },
    habitat: ['Savannah', 'Woodland', 'Wetlands', 'Grassland'],
    description:
      'Cape buffalo are among the most formidable animals on the savannah, considered one of the "Big Five." They are keystone grazers that shape grassland structure, and their wallowing creates vital water points for other species.',
    imageUrl: 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=400&q=80',
    facts: [
      { label: 'Weight', value: '500–900 kg' },
      { label: 'Herd size', value: 'Up to 2,000 individuals' },
      { label: 'Speed', value: 'Up to 57 km/h' },
      { label: 'Lifespan', value: '20–25 years' },
    ],
    threats: [
      { title: 'Disease', description: 'Foot-and-mouth disease and bovine tuberculosis spread between buffalo and domestic livestock.' },
      { title: 'Hunting', description: 'Trophy hunting pressure combined with disease management culls have reduced some populations.' },
    ],
    ecoFacts: [
      { emoji: '🌱', label: 'Grassland engineer', detail: 'Buffalo grazing patterns create a mosaic of grass heights, providing habitat niches for many smaller species.' },
    ],
    adoptionTiers: [
      { id: 'buffalo-basic', animalSlug: 'cape-buffalo', label: 'Horn Ally', amount: 10, interval: 'month', description: 'Support buffalo grassland ecosystems', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'buffalo-pro', animalSlug: 'cape-buffalo', label: 'Big Five Guardian', amount: 25, interval: 'month', description: 'Full savannah ecosystem sponsorship', perks: ['All Horn Ally perks', 'Ecosystem report', 'Photo print'] },
    ],
    fundingGoal: 20000,
    fundingRaised: 6400,
  },
  {
    slug: 'mandrill',
    name: 'Mandrill',
    species: 'Mandrillus sphinx',
    commonName: 'Mandrill',
    region: 'Central Africa',
    countries: ['Cameroon', 'Gabon', 'Republic of Congo', 'DR Congo'],
    conservationStatus: 'Vulnerable',
    population: { current: null, trend: 'Decreasing', year: 2023 },
    habitat: ['Tropical Rainforest', 'Montane Forest'],
    description:
      'The largest monkey in the world, the mandrill is famous for its vivid red and blue facial markings. They live in large social groups called hordes and are crucial seed dispersers in Central African rainforests. Bushmeat hunting and deforestation are driving their decline.',
    imageUrl: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=400&q=80',
    facts: [
      { label: 'Weight', value: 'Up to 37 kg (male)' },
      { label: 'Group size', value: 'Up to 800 in a horde' },
      { label: 'Diet', value: 'Fruits, seeds, insects, roots' },
      { label: 'Lifespan', value: 'Up to 40 years' },
    ],
    threats: [
      { title: 'Bushmeat hunting', description: 'Mandrills are hunted for food across their range, particularly in Cameroon and Gabon.' },
      { title: 'Deforestation', description: 'Logging and agricultural expansion destroy the closed canopy rainforest they depend on.' },
    ],
    ecoFacts: [
      { emoji: '🌳', label: 'Seed disperser', detail: 'Mandrills eat hundreds of fruit species and disperse seeds across vast forest areas, vital for forest regeneration.' },
    ],
    adoptionTiers: [
      { id: 'mandrill-basic', animalSlug: 'mandrill', label: 'Forest Ally', amount: 15, interval: 'month', description: 'Protect mandrill rainforest habitat', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'mandrill-pro', animalSlug: 'mandrill', label: 'Horde Protector', amount: 35, interval: 'month', description: 'Full bushmeat protection program', perks: ['All Forest Ally perks', 'Conservation report', 'Photo print'] },
    ],
    fundingGoal: 28000,
    fundingRaised: 9200,
  },
  {
    slug: 'shoebill',
    name: 'Shoebill Stork',
    species: 'Balaeniceps rex',
    commonName: 'Shoebill',
    region: 'Central Africa',
    countries: ['Uganda', 'DR Congo', 'Zambia', 'South Sudan'],
    conservationStatus: 'Vulnerable',
    population: { current: 5000, trend: 'Decreasing', year: 2023 },
    habitat: ['Papyrus Swamps', 'Wetlands', 'Floodplains'],
    description:
      'One of the most distinctive birds in Africa, the shoebill has a massive shoe-shaped bill that can swallow lungfish, baby crocodiles, and monitor lizards whole. They stand motionless for hours hunting in swamps, and were only formally described by science in the 1850s.',
    imageUrl: 'https://images.unsplash.com/photo-1557728325-b7f93a12082e?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1557728325-b7f93a12082e?w=400&q=80',
    facts: [
      { label: 'Bill length', value: '23–24 cm, shoe-shaped' },
      { label: 'Height', value: 'Up to 1.5 m' },
      { label: 'Diet', value: 'Lungfish, frogs, small crocodiles' },
      { label: 'Lifespan', value: '35+ years' },
    ],
    threats: [
      { title: 'Wetland drainage', description: 'Papyrus swamps are drained for agriculture and cattle grazing, destroying shoebill nesting sites.' },
      { title: 'Disturbance', description: 'Humans collecting fish and papyrus disturb nesting birds, leading to nest abandonment.' },
    ],
    ecoFacts: [
      { emoji: '💧', label: 'Wetland indicator', detail: 'The shoebill\'s presence indicates a healthy, intact wetland ecosystem. Their decline signals broader ecosystem collapse.' },
    ],
    adoptionTiers: [
      { id: 'shoebill-basic', animalSlug: 'shoebill', label: 'Swamp Ally', amount: 12, interval: 'month', description: 'Protect shoebill swamp habitats', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'shoebill-pro', animalSlug: 'shoebill', label: 'Wetland Warden', amount: 28, interval: 'month', description: 'Full wetland ecosystem sponsorship', perks: ['All Swamp Ally perks', 'Nest monitoring update', 'Photo print'] },
    ],
    fundingGoal: 18000,
    fundingRaised: 5600,
  },
  {
    slug: 'spotted-hyena',
    name: 'Spotted Hyena',
    species: 'Crocuta crocuta',
    commonName: 'Spotted Hyena',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Botswana', 'Zimbabwe', 'South Africa'],
    conservationStatus: 'Least Concern',
    population: { current: 47000, trend: 'Decreasing', year: 2023 },
    habitat: ['Savannah', 'Grassland', 'Woodland', 'Semi-arid'],
    description:
      'Far from being mere scavengers, spotted hyenas are highly intelligent, cooperative hunters responsible for up to 95% of their own kills. They are the most common large carnivore in Africa and play a critical role in nutrient recycling in savannah ecosystems.',
    imageUrl: 'https://images.unsplash.com/photo-1571989048872-14cb12e60de7?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571989048872-14cb12e60de7?w=400&q=80',
    facts: [
      { label: 'Bite force', value: 'Among strongest of any mammal' },
      { label: 'Social structure', value: 'Female-led clans of up to 80' },
      { label: 'Hunting success', value: 'Up to 95% on their own kills' },
      { label: 'Lifespan', value: '12–20 years' },
    ],
    threats: [
      { title: 'Persecution', description: 'Hyenas are killed by farmers protecting livestock, despite their vital ecological role.' },
      { title: 'Prey depletion', description: 'Overhunting of prey species reduces food availability for hyenas across their range.' },
    ],
    ecoFacts: [
      { emoji: '♻️', label: 'Nature\'s recycler', detail: 'Hyenas consume bones and carcasses that other predators cannot, recycling calcium and nutrients back into the soil.' },
    ],
    adoptionTiers: [
      { id: 'hyena-basic', animalSlug: 'spotted-hyena', label: 'Clan Friend', amount: 10, interval: 'month', description: 'Support hyena ecosystem role', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'hyena-pro', animalSlug: 'spotted-hyena', label: 'Pack Protector', amount: 22, interval: 'month', description: 'Coexistence program with farmers', perks: ['All Clan Friend perks', 'Ecosystem report', 'Photo print'] },
    ],
    fundingGoal: 18000,
    fundingRaised: 4800,
  },
  {
    slug: 'meerkat',
    name: 'Meerkat',
    species: 'Suricata suricatta',
    commonName: 'Meerkat',
    region: 'Southern Africa',
    countries: ['South Africa', 'Namibia', 'Botswana', 'Zimbabwe'],
    conservationStatus: 'Least Concern',
    population: { current: null, trend: 'Stable', year: 2023 },
    habitat: ['Kalahari Desert', 'Semi-arid Savannah', 'Open Grassland'],
    description:
      'Meerkats are highly social mongooses famous for their sentinel behavior — standing upright to scan for predators. They live in cooperative groups called mobs and teach their pups to handle prey. They are completely immune to many snake venoms.',
    imageUrl: 'https://images.unsplash.com/photo-1560275619-4cc5fa59d3ae?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1560275619-4cc5fa59d3ae?w=400&q=80',
    facts: [
      { label: 'Group', value: 'Mob of 20–30 individuals' },
      { label: 'Immune to', value: 'Scorpion & snake venom' },
      { label: 'Diet', value: 'Insects, scorpions, reptiles' },
      { label: 'Lifespan', value: '12–14 years in wild' },
    ],
    threats: [
      { title: 'Habitat fragmentation', description: 'Road networks and fencing disrupt meerkat mob territories in the Kalahari.' },
      { title: 'Pet trade', description: 'Meerkats are illegally captured for the exotic pet trade.' },
    ],
    ecoFacts: [
      { emoji: '🦂', label: 'Pest control', detail: 'Each meerkat consumes thousands of insects and scorpions annually, helping control pest populations in arid ecosystems.' },
    ],
    adoptionTiers: [
      { id: 'meerkat-basic', animalSlug: 'meerkat', label: 'Sentinel Ally', amount: 10, interval: 'month', description: 'Protect Kalahari meerkat habitat', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'meerkat-pro', animalSlug: 'meerkat', label: 'Mob Guardian', amount: 20, interval: 'month', description: 'Full mob habitat protection program', perks: ['All Sentinel Ally perks', 'Mob update', 'Photo print'] },
    ],
    fundingGoal: 12000,
    fundingRaised: 4500,
  },
  {
    slug: 'african-fish-eagle',
    name: 'African Fish Eagle',
    species: 'Icthyophaga vocifer',
    commonName: 'African Fish Eagle',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Uganda', 'Zambia', 'Zimbabwe'],
    conservationStatus: 'Least Concern',
    population: { current: null, trend: 'Stable', year: 2023 },
    habitat: ['Lakes', 'Rivers', 'Wetlands', 'Reservoirs'],
    description:
      'The African fish eagle is the national bird of four African countries and is considered the "voice of Africa" for its haunting call. An apex aerial predator, it plucks fish from water with its powerful talons and is an indicator species for freshwater ecosystem health.',
    imageUrl: 'https://images.unsplash.com/photo-1611689342806-0863700ce1e4?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611689342806-0863700ce1e4?w=400&q=80',
    facts: [
      { label: 'Wingspan', value: 'Up to 2 m' },
      { label: 'Dive speed', value: 'Up to 70 km/h' },
      { label: 'National bird', value: 'Zambia, Zimbabwe, Malawi & S. Sudan' },
      { label: 'Lifespan', value: '24 years' },
    ],
    threats: [
      { title: 'Water pollution', description: 'Pesticides and heavy metals bioaccumulate in fish, poisoning eagles through the food chain.' },
      { title: 'Wetland loss', description: 'Drainage of wetlands and lakes for agriculture reduces fish eagle nesting and hunting sites.' },
    ],
    ecoFacts: [
      { emoji: '🐟', label: 'Ecosystem indicator', detail: 'Fish eagle population health directly mirrors freshwater fish stock levels and lake pollution — a living barometer of Africa\'s lakes.' },
    ],
    adoptionTiers: [
      { id: 'fisheagle-basic', animalSlug: 'african-fish-eagle', label: 'Lake Ally', amount: 10, interval: 'month', description: 'Protect fish eagle freshwater habitats', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'fisheagle-pro', animalSlug: 'african-fish-eagle', label: 'Sky Guardian', amount: 22, interval: 'month', description: 'Full freshwater ecosystem sponsorship', perks: ['All Lake Ally perks', 'Waterway report', 'Photo print'] },
    ],
    fundingGoal: 14000,
    fundingRaised: 5200,
  },
  {
    slug: 'lesser-flamingo',
    name: 'Lesser Flamingo',
    species: 'Phoeniconaias minor',
    commonName: 'Lesser Flamingo',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Ethiopia', 'Namibia'],
    conservationStatus: 'Near Threatened',
    population: { current: 2600000, trend: 'Decreasing', year: 2023 },
    habitat: ['Soda Lakes', 'Salt Flats', 'Coastal Lagoons'],
    description:
      'The lesser flamingo creates one of nature\'s most spectacular spectacles — millions congregating on East Africa\'s Rift Valley soda lakes in a blaze of pink. They feed almost exclusively on cyanobacteria that thrive in highly alkaline waters, making them specialists uniquely adapted to extreme environments.',
    imageUrl: 'https://images.unsplash.com/photo-1593156157781-9fa32f6faf3b?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1593156157781-9fa32f6faf3b?w=400&q=80',
    facts: [
      { label: 'Flock size', value: 'Up to 1 million birds' },
      { label: 'Color source', value: 'Carotenoids from algae' },
      { label: 'Filter feeder', value: 'Upside-down bill filters algae' },
      { label: 'Lifespan', value: 'Up to 40 years' },
    ],
    threats: [
      { title: 'Freshwater pollution', description: 'Industrial effluents and agricultural runoff alter lake chemistry, destroying cyanobacteria food sources.' },
      { title: 'Climate change', description: 'Changing rainfall patterns affect soda lake salinity levels critical for flamingo breeding.' },
    ],
    ecoFacts: [
      { emoji: '🔵', label: 'Algae controller', detail: 'Flamingo flocks consume thousands of tonnes of cyanobacteria, preventing toxic algal blooms that would otherwise suffocate lake ecosystems.' },
    ],
    adoptionTiers: [
      { id: 'flamingo-basic', animalSlug: 'lesser-flamingo', label: 'Pink Ally', amount: 10, interval: 'month', description: 'Protect soda lake flamingo habitats', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'flamingo-pro', animalSlug: 'lesser-flamingo', label: 'Lake Guardian', amount: 22, interval: 'month', description: 'Full Rift Valley lake conservation', perks: ['All Pink Ally perks', 'Colony update', 'Photo print'] },
    ],
    fundingGoal: 22000,
    fundingRaised: 8100,
  },
  {
    slug: 'african-elephant-forest',
    name: 'Forest Elephant',
    species: 'Loxodonta cyclotis',
    commonName: 'African Forest Elephant',
    region: 'Central Africa',
    countries: ['DR Congo', 'Cameroon', 'Gabon', 'Republic of Congo'],
    conservationStatus: 'Critically Endangered',
    population: { current: 100000, trend: 'Decreasing', year: 2023 },
    habitat: ['Tropical Rainforest', 'Forest-Savannah Mosaic'],
    description:
      'Smaller and genetically distinct from the bush elephant, the forest elephant is a critically endangered ecosystem engineer of the Congo Basin. Called the "gardener of the forest," they create clearings and disperse seeds across vast distances, shaping entire forest landscapes.',
    extendedDescription:
      'Forest elephants have straight tusks adapted for moving through dense vegetation. They spend their lives within intact primary rainforest and are highly sensitive to habitat disturbance. Their loss cascades through the entire forest ecosystem — over 96 tree species in West Africa depend on elephants for seed dispersal, and without them, forests become dominated by fast-growing, less carbon-dense tree species.',
    imageUrl: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=400&q=80',
    facts: [
      { label: 'Height', value: '2.5 m (shorter than bush elephant)' },
      { label: 'Tusks', value: 'Straight, yellow (not white)' },
      { label: 'Seeds dispersed', value: 'Up to 96 tree species' },
      { label: 'Social group', value: 'Smaller than bush elephant' },
    ],
    threats: [
      { title: 'Ivory poaching', description: 'Demand for ivory has reduced forest elephant populations by 86% in just 31 years.' },
      { title: 'Deforestation', description: 'Logging and palm oil expansion in the Congo Basin destroys the intact forest they depend on.' },
      { title: 'Bushmeat trade', description: 'Calves are sometimes captured for sale when adults are poached.' },
    ],
    ecoFacts: [
      { emoji: '🌳', label: 'Carbon champion', detail: 'By dispersing seeds of large, slow-growing trees, forest elephants help maintain high-carbon forest ecosystems. Their decline releases millions of tonnes of stored carbon.' },
      { emoji: '🛤️', label: 'Road builders', detail: 'Elephant paths through dense forest create clearings and trails used by dozens of other species, earning them the title "forest engineers."' },
    ],
    adoptionTiers: [
      { id: 'forest-elephant-basic', animalSlug: 'african-elephant-forest', label: 'Forest Calf Sponsor', amount: 20, interval: 'month', description: 'Support Congo Basin forest elephants', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'forest-elephant-pro', animalSlug: 'african-elephant-forest', label: 'Rainforest Guardian', amount: 50, interval: 'month', description: 'Sponsor anti-poaching deep-forest patrols', perks: ['All Calf Sponsor perks', 'Ranger field report', 'Photo print', 'Name on donor wall'] },
    ],
    fundingGoal: 70000,
    fundingRaised: 24500,
  },
  {
    slug: 'sable-antelope',
    name: 'Sable Antelope',
    species: 'Hippotragus niger',
    commonName: 'Sable Antelope',
    region: 'Southern Africa',
    countries: ['Zimbabwe', 'Zambia', 'Mozambique', 'Tanzania', 'South Africa'],
    conservationStatus: 'Least Concern',
    population: { current: 75000, trend: 'Decreasing', year: 2023 },
    habitat: ['Miombo Woodland', 'Savannah', 'Floodplain edges'],
    description:
      'One of Africa\'s most striking antelopes, the sable antelope has distinctive swept-back horns that can reach 1.6 metres. Males are jet black with white markings; females are chestnut-brown. They are highly territorial and will defend themselves aggressively against lions.',
    imageUrl: 'https://images.unsplash.com/photo-1551316679-9c6ae9dec224?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551316679-9c6ae9dec224?w=400&q=80',
    facts: [
      { label: 'Horn length', value: 'Up to 1.6 m' },
      { label: 'Weight', value: '200–270 kg' },
      { label: 'Speed', value: 'Up to 57 km/h' },
      { label: 'Lifespan', value: '17 years' },
    ],
    threats: [
      { title: 'Habitat loss', description: 'Conversion of miombo woodland to agriculture has fragmented sable antelope populations.' },
    ],
    ecoFacts: [
      { emoji: '🌾', label: 'Grassland architect', detail: 'Sable grazing maintains grass composition in miombo woodland, benefiting dozens of smaller herbivores.' },
    ],
    adoptionTiers: [
      { id: 'sable-basic', animalSlug: 'sable-antelope', label: 'Savannah Ally', amount: 10, interval: 'month', description: 'Support sable antelope conservation', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'sable-pro', animalSlug: 'sable-antelope', label: 'Horn Guardian', amount: 22, interval: 'month', description: 'Full woodland habitat protection', perks: ['All Savannah Ally perks', 'Herd report', 'Photo print'] },
    ],
    fundingGoal: 16000,
    fundingRaised: 5100,
  },
  {
    slug: 'pygmy-hippo',
    name: 'Pygmy Hippopotamus',
    species: 'Choeropsis liberiensis',
    commonName: 'Pygmy Hippo',
    region: 'West Africa',
    countries: ['Liberia', 'Sierra Leone', 'Guinea', 'Ivory Coast'],
    conservationStatus: 'Endangered',
    population: { current: 2500, trend: 'Decreasing', year: 2023 },
    habitat: ['Lowland Tropical Forest', 'Rivers', 'Swamps'],
    description:
      'The pygmy hippo is a secretive, nocturnal relative of the common hippo, roughly a tenth of its size. Found only in the rainforests of West Africa, they are critically understudied and largely invisible to conservation programs. They are among Africa\'s most endangered and least-known large mammals.',
    imageUrl: 'https://images.unsplash.com/photo-1578153309-ecca47d37985?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578153309-ecca47d37985?w=400&q=80',
    facts: [
      { label: 'Weight', value: '160–270 kg (vs 3,200 kg for common hippo)' },
      { label: 'Activity', value: 'Primarily nocturnal' },
      { label: 'Solitary', value: 'Unlike social common hippo' },
      { label: 'Lifespan', value: '42–55 years in captivity' },
    ],
    threats: [
      { title: 'Deforestation', description: 'Logging for timber and agricultural clearing in Liberia and Ivory Coast is destroying pygmy hippo forest habitat.' },
      { title: 'Hunting', description: 'Bushmeat hunting targets pygmy hippos despite their endangered status.' },
    ],
    ecoFacts: [
      { emoji: '💧', label: 'Forest waterways', detail: 'Pygmy hippos create and maintain small paths through dense forest vegetation, creating waterways for other species.' },
    ],
    adoptionTiers: [
      { id: 'pygmy-hippo-basic', animalSlug: 'pygmy-hippo', label: 'Forest River Ally', amount: 18, interval: 'month', description: 'Protect pygmy hippo rainforest habitat', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'pygmy-hippo-pro', animalSlug: 'pygmy-hippo', label: 'Rainforest Guardian', amount: 40, interval: 'month', description: 'Full forest patrol sponsorship', perks: ['All Forest River Ally perks', 'Forest camera update', 'Photo print'] },
    ],
    fundingGoal: 28000,
    fundingRaised: 9800,
  },
  {
    slug: 'african-wild-ass',
    name: 'African Wild Ass',
    species: 'Equus africanus',
    commonName: 'African Wild Ass',
    region: 'North Africa',
    countries: ['Ethiopia', 'Eritrea', 'Somalia'],
    conservationStatus: 'Critically Endangered',
    population: { current: 600, trend: 'Decreasing', year: 2023 },
    habitat: ['Rocky Desert', 'Semi-arid Grassland', 'Mountain plateau'],
    description:
      'The ancestor of all domestic donkeys, the African wild ass is one of the rarest animals on Earth. Fewer than 600 remain in the wild in the Horn of Africa. They are perfectly adapted to arid environments, surviving on minimal water, but face extreme pressure from hunting and competition with livestock.',
    imageUrl: 'https://images.unsplash.com/photo-1553257805-8b0ab3f45fa0?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1553257805-8b0ab3f45fa0?w=400&q=80',
    facts: [
      { label: 'Population', value: 'Fewer than 600 in the wild' },
      { label: 'Ancestor of', value: 'All domestic donkeys' },
      { label: 'Water need', value: 'Can survive 3 days without water' },
      { label: 'Speed', value: 'Up to 70 km/h' },
    ],
    threats: [
      { title: 'Hunting for traditional medicine', description: 'Body parts are used in traditional medicine in the Horn of Africa.' },
      { title: 'Hybridization', description: 'Interbreeding with domestic donkeys dilutes the wild gene pool.' },
    ],
    ecoFacts: [
      { emoji: '🏜️', label: 'Desert ecosystem', detail: 'Wild asses open up tough desert vegetation, creating grazing patches used by smaller desert animals.' },
    ],
    adoptionTiers: [
      { id: 'wildass-basic', animalSlug: 'african-wild-ass', label: 'Desert Ally', amount: 20, interval: 'month', description: 'Protect the ancestor of all donkeys', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'wildass-pro', animalSlug: 'african-wild-ass', label: 'Horn of Africa Guardian', amount: 45, interval: 'month', description: 'Full anti-poaching and breeding program', perks: ['All Desert Ally perks', 'Field report', 'Photo print'] },
    ],
    fundingGoal: 30000,
    fundingRaised: 10200,
  },
  {
    slug: 'secretary-bird',
    name: 'Secretary Bird',
    species: 'Sagittarius serpentarius',
    commonName: 'Secretary Bird',
    region: 'Southern Africa',
    countries: ['South Africa', 'Namibia', 'Botswana', 'Kenya', 'Tanzania'],
    conservationStatus: 'Endangered',
    population: { current: null, trend: 'Decreasing', year: 2023 },
    habitat: ['Open Grassland', 'Savannah', 'Thornbush'],
    description:
      'The secretary bird is one of Africa\'s most iconic birds — a large raptor that walks through the savannah on long stilt-like legs, stomping venomous snakes to death with powerful kicks. They are master snake hunters and an indicator of grassland ecosystem health.',
    imageUrl: 'https://images.unsplash.com/photo-1444464666168-49d633b86797?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1444464666168-49d633b86797?w=400&q=80',
    facts: [
      { label: 'Height', value: 'Up to 1.35 m' },
      { label: 'Kick force', value: '5× their body weight' },
      { label: 'Walking', value: 'Up to 20 km per day' },
      { label: 'Prey', value: 'Snakes, lizards, insects, small mammals' },
    ],
    threats: [
      { title: 'Grassland loss', description: 'Conversion of natural grassland to cropland eliminates secretary bird foraging habitat.' },
      { title: 'Pesticide use', description: 'Agricultural pesticides kill insects and small prey, reducing food availability.' },
    ],
    ecoFacts: [
      { emoji: '🐍', label: 'Snake controller', detail: 'Secretary birds kill thousands of venomous snakes annually, protecting both wildlife and farming communities from dangerous bites.' },
    ],
    adoptionTiers: [
      { id: 'secretary-bird-basic', animalSlug: 'secretary-bird', label: 'Grassland Ally', amount: 12, interval: 'month', description: 'Support secretary bird habitat', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'secretary-bird-pro', animalSlug: 'secretary-bird', label: 'Snake Stomper Sponsor', amount: 28, interval: 'month', description: 'Full grassland conservation program', perks: ['All Grassland Ally perks', 'Breeding report', 'Photo print'] },
    ],
    fundingGoal: 16000,
    fundingRaised: 4900,
  },
  {
    slug: 'chimpanzee',
    name: 'Chimpanzee',
    species: 'Pan troglodytes',
    commonName: 'Common Chimpanzee',
    region: 'West Africa',
    countries: ['DR Congo', 'Cameroon', 'Gabon', 'Uganda', 'Guinea', 'Ivory Coast'],
    conservationStatus: 'Endangered',
    population: { current: 170000, trend: 'Decreasing', year: 2023 },
    habitat: ['Tropical Rainforest', 'Woodland', 'Savannah mosaic'],
    description:
      'Our closest living relative sharing 98.7% of our DNA, chimpanzees are highly intelligent tool-users, social learners, and even wagers of complex warfare. They are critically endangered by deforestation, bushmeat hunting, and disease, including outbreaks of Ebola virus which have killed entire communities.',
    extendedDescription:
      'Chimpanzees have rich cultures — different chimp communities across Africa have developed unique tool-use traditions, social practices, and even "languages" of calls. They grieve their dead, feel empathy, and form lifelong friendships. Yet in just the past century, their population has plummeted from over 1 million to under 170,000 individuals.',
    imageUrl: 'https://images.unsplash.com/photo-1505148230895-d9a785a555fa?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1505148230895-d9a785a555fa?w=400&q=80',
    facts: [
      { label: 'DNA with humans', value: '98.7%' },
      { label: 'Tool use', value: 'Sticks, stones, leaves' },
      { label: 'Communication', value: '66+ unique calls' },
      { label: 'Lifespan', value: '40–50 years in wild' },
    ],
    threats: [
      { title: 'Bushmeat trade', description: 'Chimpanzees are hunted for food across Central and West Africa, with infants captured for the illegal pet trade.' },
      { title: 'Deforestation', description: 'Industrial logging, palm oil, and cocoa farming destroy and fragment chimpanzee habitat.' },
      { title: 'Disease', description: 'Ebola outbreaks and respiratory diseases transmitted from humans have devastated entire chimp populations.' },
    ],
    ecoFacts: [
      { emoji: '🛠️', label: 'Tool innovators', detail: 'Chimps use stone tools to crack nuts, sticks to fish termites, and leaves as sponges — traditions passed between generations like human culture.' },
      { emoji: '🌳', label: 'Seed dispersers', detail: 'Chimps disperse seeds of over 200 plant species, making them irreplaceable architects of tropical forest structure.' },
    ],
    adoptionTiers: [
      { id: 'chimp-basic', animalSlug: 'chimpanzee', label: 'Troop Ally', amount: 20, interval: 'month', description: 'Protect chimpanzee forest communities', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'chimp-pro', animalSlug: 'chimpanzee', label: 'Forest Kin Sponsor', amount: 50, interval: 'month', description: 'Sponsor a sanctuary rehabilitation program', perks: ['All Troop Ally perks', 'Sanctuary update', 'Photo print', 'Name on donor wall'] },
    ],
    fundingGoal: 55000,
    fundingRaised: 21800,
  },
  {
    slug: 'nile-monitor',
    name: 'Nile Monitor',
    species: 'Varanus niloticus',
    commonName: 'Nile Monitor Lizard',
    region: 'East Africa',
    countries: ['Kenya', 'Tanzania', 'Uganda', 'Egypt', 'South Africa'],
    conservationStatus: 'Least Concern',
    population: { current: null, trend: 'Stable', year: 2023 },
    habitat: ['Rivers', 'Lakes', 'Wetlands', 'Savannah'],
    description:
      'Africa\'s largest lizard, the Nile monitor is a highly adaptable and intelligent reptile found near water bodies across sub-Saharan Africa. They are important predators of crocodile eggs, fish, and small mammals, helping regulate populations throughout the food chain.',
    imageUrl: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=400&q=80',
    facts: [
      { label: 'Length', value: 'Up to 2 m' },
      { label: 'Weight', value: 'Up to 10 kg' },
      { label: 'Tongue', value: 'Forked, detects scent' },
      { label: 'Swimming', value: 'Excellent swimmer' },
    ],
    threats: [
      { title: 'Skin trade', description: 'Monitor skins are illegally harvested for the exotic leather trade.' },
      { title: 'Wetland loss', description: 'Drainage of wetland habitats reduces monitor food availability and breeding sites.' },
    ],
    ecoFacts: [
      { emoji: '🥚', label: 'Crocodile egg predator', detail: 'Monitors excavate and eat crocodile egg nests, naturally regulating crocodile populations alongside other prey species.' },
    ],
    adoptionTiers: [
      { id: 'monitor-basic', animalSlug: 'nile-monitor', label: 'River Ally', amount: 8, interval: 'month', description: 'Protect monitor wetland habitats', perks: ['Digital certificate', 'Monthly update'] },
      { id: 'monitor-pro', animalSlug: 'nile-monitor', label: 'Riparian Guardian', amount: 18, interval: 'month', description: 'Riverine ecosystem conservation', perks: ['All River Ally perks', 'Wetland report', 'Photo print'] },
    ],
    fundingGoal: 10000,
    fundingRaised: 3200,
  },
]

export const REGIONS: Region[] = [
  {
    id: 'east-africa',
    name: 'East Africa',
    description:
      'Home to the Great Serengeti, the Maasai Mara, Mount Kilimanjaro, and the Great Rift Valley. East Africa hosts the largest terrestrial mammal migration on Earth and extraordinary biodiversity across savannahs, highlands, and coastal forests.',
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80',
    keyHabitats: ['Savannah', 'Highland Forest', 'Wetlands', 'Coastal Forest', 'Great Rift Valley'],
    threatLevel: 'High',
    countries: [
      { name: 'Kenya', code: 'KE', flag: '🇰🇪', habitat: ['Savannah', 'Highland', 'Coastal'], featuredAnimals: ['african-elephant', 'african-lion', 'cheetah'] },
      { name: 'Tanzania', code: 'TZ', flag: '🇹🇿', habitat: ['Savannah', 'Mountain', 'Coastal'], featuredAnimals: ['african-lion', 'hippopotamus', 'cheetah'] },
      { name: 'Uganda', code: 'UG', flag: '🇺🇬', habitat: ['Forest', 'Wetlands', 'Savannah'], featuredAnimals: ['mountain-gorilla', 'hippopotamus'] },
      { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', habitat: ['Highland', 'Semi-arid', 'Forest'], featuredAnimals: ['ethiopian-wolf', 'grevy-zebra'] },
      { name: 'Rwanda', code: 'RW', flag: '🇷🇼', habitat: ['Montane Forest', 'Savannah'], featuredAnimals: ['mountain-gorilla'] },
    ],
  },
  {
    id: 'southern-africa',
    name: 'Southern Africa',
    description:
      'A region of stunning diversity, from the Namib and Kalahari deserts to the lush forests of the Cape. Southern Africa is home to the iconic "Big Five" and some of the continent\'s most successful conservation stories.',
    imageUrl: 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=1200&q=80',
    keyHabitats: ['Savannah', 'Desert', 'Fynbos', 'Coastal', 'Wetlands'],
    threatLevel: 'Moderate',
    countries: [
      { name: 'South Africa', code: 'ZA', flag: '🇿🇦', habitat: ['Savannah', 'Fynbos', 'Coastal', 'Desert'], featuredAnimals: ['black-rhino', 'white-rhino', 'african-penguin'] },
      { name: 'Botswana', code: 'BW', flag: '🇧🇼', habitat: ['Savannah', 'Wetlands', 'Desert'], featuredAnimals: ['african-elephant', 'african-wild-dog'] },
      { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', habitat: ['Savannah', 'Forest', 'Wetlands'], featuredAnimals: ['black-rhino', 'african-elephant'] },
      { name: 'Namibia', code: 'NA', flag: '🇳🇦', habitat: ['Desert', 'Savannah', 'Coastal'], featuredAnimals: ['black-rhino', 'cheetah'] },
      { name: 'Zambia', code: 'ZM', flag: '🇿🇲', habitat: ['Savannah', 'Wetlands', 'Forest'], featuredAnimals: ['african-elephant', 'hippopotamus'] },
    ],
  },
  {
    id: 'central-africa',
    name: 'Central Africa',
    description:
      'The Congo Basin contains the world\'s second-largest tropical rainforest, a staggering reservoir of biodiversity. Central Africa is home to great apes, forest elephants, and thousands of endemic species found nowhere else on Earth.',
    imageUrl: 'https://images.unsplash.com/photo-1580204928328-eef2ac1c7b19?w=1200&q=80',
    keyHabitats: ['Tropical Rainforest', 'River Systems', 'Wetlands', 'Montane Forest'],
    threatLevel: 'Critical',
    countries: [
      { name: 'DR Congo', code: 'CD', flag: '🇨🇩', habitat: ['Rainforest', 'Savannah', 'Wetlands'], featuredAnimals: ['mountain-gorilla', 'bonobo', 'okapi'] },
      { name: 'Cameroon', code: 'CM', flag: '🇨🇲', habitat: ['Rainforest', 'Savannah', 'Highland'], featuredAnimals: ['mountain-gorilla'] },
      { name: 'Gabon', code: 'GA', flag: '🇬🇦', habitat: ['Rainforest', 'Coastal', 'Savannah'], featuredAnimals: [] },
      { name: 'Republic of Congo', code: 'CG', flag: '🇨🇬', habitat: ['Rainforest', 'Savannah'], featuredAnimals: [] },
      { name: 'Rwanda', code: 'RW', flag: '🇷🇼', habitat: ['Montane Forest', 'Savannah'], featuredAnimals: ['mountain-gorilla'] },
    ],
  },
  {
    id: 'west-africa',
    name: 'West Africa',
    description:
      'Stretching from Senegal to Nigeria, West Africa holds diverse ecosystems from the Sahel to coastal rainforests. Rapid population growth and agriculture expansion have put enormous pressure on the region\'s remaining wildlife corridors.',
    imageUrl: 'https://images.unsplash.com/photo-1504892716950-5f26b0434ad8?w=1200&q=80',
    keyHabitats: ['Coastal Forest', 'Sahel', 'Mangroves', 'Wetlands', 'Savannah'],
    threatLevel: 'Critical',
    countries: [
      { name: 'Nigeria', code: 'NG', flag: '🇳🇬', habitat: ['Forest', 'Savannah', 'Coastal'], featuredAnimals: ['african-wild-cat'] },
      { name: 'Ghana', code: 'GH', flag: '🇬🇭', habitat: ['Forest', 'Savannah', 'Coastal'], featuredAnimals: [] },
      { name: 'Senegal', code: 'SN', flag: '🇸🇳', habitat: ['Sahel', 'Coastal', 'Savannah'], featuredAnimals: [] },
      { name: 'Ivory Coast', code: 'CI', flag: '🇨🇮', habitat: ['Rainforest', 'Savannah', 'Coastal'], featuredAnimals: [] },
      { name: 'Guinea', code: 'GN', flag: '🇬🇳', habitat: ['Forest', 'Highland', 'Coastal'], featuredAnimals: [] },
    ],
  },
  {
    id: 'north-africa',
    name: 'North Africa',
    description:
      'Dominated by the Sahara Desert, North Africa is nonetheless rich in unique wildlife adapted to extreme conditions. Mediterranean coastal habitats, oasis ecosystems, and the Atlas Mountains support remarkable endemic species.',
    imageUrl: 'https://images.unsplash.com/photo-1548613053-22087dd8edb8?w=1200&q=80',
    keyHabitats: ['Sahara Desert', 'Mediterranean Coast', 'Atlas Mountains', 'Oasis', 'Wetlands'],
    threatLevel: 'High',
    countries: [
      { name: 'Morocco', code: 'MA', flag: '🇲🇦', habitat: ['Mountain', 'Desert', 'Coastal', 'Forest'], featuredAnimals: ['caracal'] },
      { name: 'Egypt', code: 'EG', flag: '🇪🇬', habitat: ['Desert', 'River', 'Coastal'], featuredAnimals: ['nile-crocodile'] },
      { name: 'Algeria', code: 'DZ', flag: '🇩🇿', habitat: ['Desert', 'Mediterranean', 'Mountain'], featuredAnimals: ['caracal'] },
      { name: 'Tunisia', code: 'TN', flag: '🇹🇳', habitat: ['Desert', 'Mediterranean', 'Wetlands'], featuredAnimals: [] },
      { name: 'Libya', code: 'LY', flag: '🇱🇾', habitat: ['Desert', 'Mediterranean', 'Coastal'], featuredAnimals: [] },
    ],
  },
]

export const DONATION_TIERS: DonationTier[] = [
  {
    id: 'supporter',
    label: 'Supporter',
    amount: 10,
    frequency: 'monthly',
    description: 'Help fund vital field research and community education programs across Africa.',
    perks: ['Monthly newsletter', 'Digital impact report', 'Supporter badge'],
    featured: false,
  },
  {
    id: 'guardian',
    label: 'Guardian',
    amount: 25,
    frequency: 'monthly',
    description: 'Protect critical wildlife corridors and fund anti-poaching patrols.',
    perks: ['All Supporter perks', 'Personalized thank-you certificate', 'Name on donor wall', 'Quarterly photo update'],
    featured: true,
  },
  {
    id: 'champion',
    label: 'Champion',
    amount: 50,
    frequency: 'monthly',
    description: 'Fund dedicated anti-poaching units and habitat restoration projects.',
    perks: ['All Guardian perks', 'Exclusive quarterly video update', 'Merchandise discount (20%)', 'Priority event access'],
    featured: false,
  },
  {
    id: 'hero',
    label: 'Hero',
    amount: 100,
    frequency: 'monthly',
    description: 'Become a named sponsor of a dedicated conservation zone in Africa.',
    perks: ['All Champion perks', 'Annual field call with a conservationist', 'Named sponsorship of a conservation unit', 'VIP annual report'],
    featured: false,
  },
]

export const MEMBERSHIP_TIERS: MembershipTier[] = [
  {
    id: 'community',
    label: 'Community Member',
    description: 'Raise awareness and support Earth Protect\'s mission through your network. No minimum commitment required.',
    commitment: 'No minimum',
    perks: ['Monthly digest newsletter', 'Access to community forum', 'Digital Earth Protect badge', 'Exclusive online events'],
    applicationRequired: false,
  },
  {
    id: 'volunteer',
    label: 'Field Volunteer',
    description: 'Join ground-level conservation projects across Africa. Work alongside rangers, researchers, and local communities.',
    commitment: '1 week minimum on-site',
    perks: ['All Community perks', 'Training & safety materials', 'Travel grant consideration', 'Reference letter', 'Volunteer certification'],
    applicationRequired: true,
  },
  {
    id: 'ambassador',
    label: 'Brand Ambassador',
    description: 'Represent Earth Protect in your region. Build partnerships, run fundraising events, and grow our mission.',
    commitment: '5 hours/month minimum',
    perks: ['All Community perks', 'Official Earth Protect Ambassador kit', 'Speaking & media opportunities', 'Revenue sharing on referrals (5%)', 'Direct line to leadership team'],
    applicationRequired: true,
  },
]

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'tee-elephant',
    slug: 'elephant-guardian-tee',
    name: 'Elephant Guardian T-Shirt',
    description: 'Premium organic cotton tee featuring a hand-illustrated African elephant design. Wear your support for the gentle giants of Africa.',
    price: 35,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    category: 'apparel',
    tags: ['elephant', 'clothing', 'organic'],
    inStock: true,
    proceedsNote: '50% of proceeds directly fund elephant conservation in Kenya.',
  },
  {
    id: 'print-big-five',
    slug: 'big-five-art-print',
    name: 'Big Five Art Print Set',
    description: 'A stunning set of 5 A3 giclée prints featuring the iconic Big Five: lion, leopard, elephant, buffalo, and rhino. Museum-quality archival ink.',
    price: 65,
    imageUrl: 'https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?w=600&q=80',
    category: 'prints',
    tags: ['art', 'big five', 'print', 'gift'],
    inStock: true,
    proceedsNote: '60% of proceeds support Big Five habitat conservation.',
  },
  {
    id: 'tote-pangolin',
    slug: 'pangolin-tote-bag',
    name: 'Pangolin Tote Bag',
    description: 'Durable, reusable canvas tote bag with an adorable pangolin illustration. Say no to plastic and say yes to pangolin protection.',
    price: 22,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    category: 'accessories',
    tags: ['pangolin', 'bag', 'eco-friendly'],
    inStock: true,
    proceedsNote: '100% of proceeds help fight pangolin trafficking.',
  },
  {
    id: 'hoodie-lion',
    slug: 'lion-mane-hoodie',
    name: 'Lion Mane Hoodie',
    description: 'Cozy premium hoodie with a majestic lion illustration. Available in earthy savannah tones. Made from recycled materials.',
    price: 75,
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80',
    category: 'apparel',
    tags: ['lion', 'clothing', 'recycled'],
    inStock: true,
    proceedsNote: '40% of proceeds support lion conservation across Africa.',
  },
  {
    id: 'mug-rhino',
    slug: 'rhino-conservation-mug',
    name: 'Rhino Conservation Mug',
    description: 'Start your day knowing you\'re making a difference. This 350ml ceramic mug features a bold black rhino design with conservation facts.',
    price: 18,
    imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'accessories',
    tags: ['rhino', 'mug', 'gift'],
    inStock: true,
    proceedsNote: '70% of proceeds directly fund black rhino anti-poaching units.',
  },
  {
    id: 'pin-cheetah',
    slug: 'cheetah-enamel-pin',
    name: 'Cheetah Enamel Pin',
    description: 'Hand-crafted hard enamel pin featuring a running cheetah. Perfect for bags, jackets, and lapels. Gold plating, 3cm.',
    price: 12,
    imageUrl: 'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?w=600&q=80',
    category: 'accessories',
    tags: ['cheetah', 'pin', 'collectible'],
    inStock: true,
    proceedsNote: '80% of proceeds support cheetah habitat protection in Tanzania.',
  },
  {
    id: 'wallpaper-pack',
    slug: 'african-wildlife-wallpaper-pack',
    name: 'African Wildlife Digital Wallpaper Pack',
    description: 'A collection of 20 stunning high-resolution wildlife photographs for desktop and mobile. Includes elephant, lion, leopard, gorilla, and more.',
    price: 8,
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80',
    category: 'digital',
    tags: ['digital', 'wallpaper', 'photography'],
    inStock: true,
    proceedsNote: '100% of proceeds support wildlife photography and conservation awareness.',
  },
  {
    id: 'cap-wilddog',
    slug: 'wild-dog-cap',
    name: 'Painted Wolf Cap',
    description: 'Embroidered cap with the distinctive spotted pattern of the African wild dog. Adjustable strap, one size fits all.',
    price: 28,
    imageUrl: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&q=80',
    category: 'apparel',
    tags: ['wild dog', 'cap', 'clothing'],
    inStock: true,
    proceedsNote: '60% of proceeds fund African wild dog pack conservation.',
  },
  {
    id: 'print-gorilla',
    slug: 'mountain-gorilla-portrait',
    name: 'Mountain Gorilla Portrait Print',
    description: 'A striking A2 photographic portrait of a mountain gorilla, printed on premium archival paper. Certificate of conservation contribution included.',
    price: 45,
    imageUrl: 'https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=600&q=80',
    category: 'prints',
    tags: ['gorilla', 'print', 'photograph', 'gift'],
    inStock: true,
    proceedsNote: '75% of proceeds go directly to mountain gorilla habitat protection in the Virungas.',
  },
  {
    id: 'tee-penguin',
    slug: 'african-penguin-tee',
    name: 'African Penguin T-Shirt',
    description: 'Lightweight, breathable tee featuring a cute African penguin illustration. A playful reminder that Africa\'s wildlife extends to its coastlines.',
    price: 30,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    category: 'apparel',
    tags: ['penguin', 'clothing', 'coastal'],
    inStock: true,
    proceedsNote: '50% of proceeds support African penguin colony protection.',
  },
]

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'serengeti-wildebeest-migration-2024',
    title: 'The Great Wildebeest Migration: 2024 Season Update',
    excerpt: 'Over 1.5 million wildebeest have begun their annual journey across the Serengeti. This year\'s migration shows encouraging signs for the ecosystem\'s health.',
    content: '',
    author: 'Dr. Amara Osei',
    publishedAt: '2024-07-15',
    tags: ['migration', 'wildebeest', 'Serengeti', 'Tanzania'],
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
    category: 'news',
  },
  {
    slug: 'black-rhino-population-milestone',
    title: 'Black Rhino Numbers Cross 6,000 — A Conservation Milestone',
    excerpt: 'For the first time in decades, the black rhino population has exceeded 6,000 individuals, marking a major victory for conservation efforts across southern Africa.',
    content: '',
    author: 'Sarah Kimani',
    publishedAt: '2024-06-28',
    tags: ['rhino', 'conservation', 'southern Africa', 'milestone'],
    imageUrl: 'https://images.unsplash.com/photo-1598885159317-6c7f752e4f61?w=800&q=80',
    category: 'story',
  },
  {
    slug: 'mountain-gorilla-census-results',
    title: 'Mountain Gorilla Census: Population Climbs to 1,063',
    excerpt: 'The latest census confirms a growing mountain gorilla population — a testament to decades of international conservation effort and community engagement in the Virunga landscape.',
    content: '',
    author: 'Jean-Paul Habimana',
    publishedAt: '2024-06-10',
    tags: ['gorilla', 'census', 'Virunga', 'Rwanda'],
    imageUrl: 'https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=800&q=80',
    category: 'research',
  },
  {
    slug: 'pangolin-trafficking-crackdown',
    title: 'Major Pangolin Trafficking Network Dismantled in Central Africa',
    excerpt: 'A joint operation between rangers and international law enforcement has dismantled a major pangolin trafficking network, rescuing 47 live pangolins.',
    content: '',
    author: 'Emmanuel Diallo',
    publishedAt: '2024-05-22',
    tags: ['pangolin', 'trafficking', 'law enforcement', 'rescue'],
    imageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=800&q=80',
    category: 'news',
  },
  {
    slug: 'community-conservation-west-africa',
    title: 'How Local Communities Are Leading Conservation in West Africa',
    excerpt: 'Grassroots conservation initiatives led by local communities are proving more effective than top-down approaches in protecting wildlife corridors in Nigeria and Ghana.',
    content: '',
    author: 'Fatima Al-Hassan',
    publishedAt: '2024-05-05',
    tags: ['community', 'West Africa', 'conservation', 'Nigeria', 'Ghana'],
    imageUrl: 'https://images.unsplash.com/photo-1504892716950-5f26b0434ad8?w=800&q=80',
    category: 'story',
  },
  {
    slug: 'cheetah-gps-tracking-program',
    title: 'New GPS Tracking Program Reveals Cheetah Migration Patterns',
    excerpt: 'A new GPS collar program tracking 28 cheetahs across Tanzania and Kenya has revealed previously unknown migration corridors, informing urgent habitat protection efforts.',
    content: '',
    author: 'Dr. Lena Müller',
    publishedAt: '2024-04-18',
    tags: ['cheetah', 'GPS', 'research', 'habitat'],
    imageUrl: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80',
    category: 'research',
  },
]
