import type {
  Animal,
  Region,
  DonationTier,
  MembershipTier,
  ShopItem,
  NavLink,
  ImpactStat,
  BlogPost,
} from '@/types'

export const NAV_LINKS: NavLink[] = [
  { label: 'Animals', href: '/animals' },
  { label: 'Regions', href: '/regions' },
  { label: 'Blog', href: '/blog' },
  { label: 'Shop', href: '/shop' },
  { label: 'About', href: '/about' },
]

export const IMPACT_STATS: ImpactStat[] = [
  { value: '1,200+', label: 'Animals Protected', icon: 'shield' },
  { value: '850K', label: 'Hectares Conserved', icon: 'trees' },
  { value: '42', label: 'Partner Countries', icon: 'globe' },
  { value: '18K+', label: 'Community Members', icon: 'users' },
]

export const ANIMALS: Animal[] = []

export const REGIONS: Region[] = [
  {
    id: 'east-africa',
    name: 'East Africa',
    description:
      'Home to the Great Serengeti, the Maasai Mara, Mount Kilimanjaro, and the Great Rift Valley. East Africa hosts the largest terrestrial mammal migration on Earth and extraordinary biodiversity across savannahs, highlands, and coastal forests.',
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80',
    keyHabitats: ['Savannah', 'Highland Forest', 'Wetlands', 'Coastal Forest', 'Great Rift Valley'],
    threatLevel: 'High',
    countries: [
      { name: 'Kenya', code: 'KE', flag: '🇰🇪', habitat: ['Savannah', 'Highland', 'Coastal'], featuredAnimals: ['african-elephant', 'african-lion', 'cheetah'] },
      { name: 'Tanzania', code: 'TZ', flag: '🇹🇿', habitat: ['Savannah', 'Mountain', 'Coastal'], featuredAnimals: ['african-lion', 'hippopotamus', 'cheetah'] },
      { name: 'Uganda', code: 'UG', flag: '🇺🇬', habitat: ['Forest', 'Wetlands', 'Savannah'], featuredAnimals: ['mountain-gorilla', 'hippopotamus'] },
      { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', habitat: ['Highland', 'Semi-arid', 'Forest'], featuredAnimals: ['ethiopian-wolf', 'grevy-zebra'] },
      { name: 'Rwanda', code: 'RW', flag: '🇷🇼', habitat: ['Montane Forest', 'Savannah'], featuredAnimals: ['mountain-gorilla'] },
    ],
  },
  {
    id: 'southern-africa',
    name: 'Southern Africa',
    description:
      'A region of stunning diversity, from the Namib and Kalahari deserts to the lush forests of the Cape. Southern Africa is home to the iconic "Big Five" and some of the continent\'s most successful conservation stories.',
    imageUrl: 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=1200&q=80',
    keyHabitats: ['Savannah', 'Desert', 'Fynbos', 'Coastal', 'Wetlands'],
    threatLevel: 'Moderate',
    countries: [
      { name: 'South Africa', code: 'ZA', flag: '🇿🇦', habitat: ['Savannah', 'Fynbos', 'Coastal', 'Desert'], featuredAnimals: ['black-rhino', 'white-rhino', 'african-penguin'] },
      { name: 'Botswana', code: 'BW', flag: '🇧🇼', habitat: ['Savannah', 'Wetlands', 'Desert'], featuredAnimals: ['african-elephant', 'african-wild-dog'] },
      { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', habitat: ['Savannah', 'Forest', 'Wetlands'], featuredAnimals: ['black-rhino', 'african-elephant'] },
      { name: 'Namibia', code: 'NA', flag: '🇳🇦', habitat: ['Desert', 'Savannah', 'Coastal'], featuredAnimals: ['black-rhino', 'cheetah'] },
      { name: 'Zambia', code: 'ZM', flag: '🇿🇲', habitat: ['Savannah', 'Wetlands', 'Forest'], featuredAnimals: ['african-elephant', 'hippopotamus'] },
    ],
  },
  {
    id: 'central-africa',
    name: 'Central Africa',
    description:
      'The Congo Basin contains the world\'s second-largest tropical rainforest, a staggering reservoir of biodiversity. Central Africa is home to great apes, forest elephants, and thousands of endemic species found nowhere else on Earth.',
    imageUrl: 'https://images.unsplash.com/photo-1580204928328-eef2ac1c7b19?w=1200&q=80',
    keyHabitats: ['Tropical Rainforest', 'River Systems', 'Wetlands', 'Montane Forest'],
    threatLevel: 'Critical',
    countries: [
      { name: 'DR Congo', code: 'CD', flag: '🇨🇩', habitat: ['Rainforest', 'Savannah', 'Wetlands'], featuredAnimals: ['mountain-gorilla', 'bonobo', 'okapi'] },
      { name: 'Cameroon', code: 'CM', flag: '🇨🇲', habitat: ['Rainforest', 'Savannah', 'Highland'], featuredAnimals: ['mountain-gorilla'] },
      { name: 'Gabon', code: 'GA', flag: '🇬🇦', habitat: ['Rainforest', 'Coastal', 'Savannah'], featuredAnimals: [] },
      { name: 'Republic of Congo', code: 'CG', flag: '🇨🇬', habitat: ['Rainforest', 'Savannah'], featuredAnimals: [] },
      { name: 'Rwanda', code: 'RW', flag: '🇷🇼', habitat: ['Montane Forest', 'Savannah'], featuredAnimals: ['mountain-gorilla'] },
    ],
  },
  {
    id: 'west-africa',
    name: 'West Africa',
    description:
      'Stretching from Senegal to Nigeria, West Africa holds diverse ecosystems from the Sahel to coastal rainforests. Rapid population growth and agriculture expansion have put enormous pressure on the region\'s remaining wildlife corridors.',
    imageUrl: 'https://images.unsplash.com/photo-1504892716950-5f26b0434ad8?w=1200&q=80',
    keyHabitats: ['Coastal Forest', 'Sahel', 'Mangroves', 'Wetlands', 'Savannah'],
    threatLevel: 'Critical',
    countries: [
      { name: 'Nigeria', code: 'NG', flag: '🇳🇬', habitat: ['Forest', 'Savannah', 'Coastal'], featuredAnimals: ['african-wild-cat'] },
      { name: 'Ghana', code: 'GH', flag: '🇬🇭', habitat: ['Forest', 'Savannah', 'Coastal'], featuredAnimals: [] },
      { name: 'Senegal', code: 'SN', flag: '🇸🇳', habitat: ['Sahel', 'Coastal', 'Savannah'], featuredAnimals: [] },
      { name: 'Ivory Coast', code: 'CI', flag: '🇨🇮', habitat: ['Rainforest', 'Savannah', 'Coastal'], featuredAnimals: [] },
      { name: 'Guinea', code: 'GN', flag: '🇬🇳', habitat: ['Forest', 'Highland', 'Coastal'], featuredAnimals: [] },
    ],
  },
  {
    id: 'north-africa',
    name: 'North Africa',
    description:
      'Dominated by the Sahara Desert, North Africa is nonetheless rich in unique wildlife adapted to extreme conditions. Mediterranean coastal habitats, oasis ecosystems, and the Atlas Mountains support remarkable endemic species.',
    imageUrl: 'https://images.unsplash.com/photo-1548613053-22087dd8edb8?w=1200&q=80',
    keyHabitats: ['Sahara Desert', 'Mediterranean Coast', 'Atlas Mountains', 'Oasis', 'Wetlands'],
    threatLevel: 'High',
    countries: [
      { name: 'Morocco', code: 'MA', flag: '🇲🇦', habitat: ['Mountain', 'Desert', 'Coastal', 'Forest'], featuredAnimals: ['caracal'] },
      { name: 'Egypt', code: 'EG', flag: '🇪🇬', habitat: ['Desert', 'River', 'Coastal'], featuredAnimals: ['nile-crocodile'] },
      { name: 'Algeria', code: 'DZ', flag: '🇩🇿', habitat: ['Desert', 'Mediterranean', 'Mountain'], featuredAnimals: ['caracal'] },
      { name: 'Tunisia', code: 'TN', flag: '🇹🇳', habitat: ['Desert', 'Mediterranean', 'Wetlands'], featuredAnimals: [] },
      { name: 'Libya', code: 'LY', flag: '🇱🇾', habitat: ['Desert', 'Mediterranean', 'Coastal'], featuredAnimals: [] },
    ],
  },
]

export const DONATION_TIERS: DonationTier[] = [
  {
    id: 'supporter',
    label: 'Supporter',
    amount: 10,
    frequency: 'monthly',
    description: 'Help fund vital field research and community education programs across Africa.',
    perks: ['Monthly newsletter', 'Digital impact report', 'Supporter badge'],
    featured: false,
  },
  {
    id: 'guardian',
    label: 'Guardian',
    amount: 25,
    frequency: 'monthly',
    description: 'Protect critical wildlife corridors and fund anti-poaching patrols.',
    perks: ['All Supporter perks', 'Personalized thank-you certificate', 'Name on donor wall', 'Quarterly photo update'],
    featured: true,
  },
  {
    id: 'champion',
    label: 'Champion',
    amount: 50,
    frequency: 'monthly',
    description: 'Fund dedicated anti-poaching units and habitat restoration projects.',
    perks: ['All Guardian perks', 'Exclusive quarterly video update', 'Merchandise discount (20%)', 'Priority event access'],
    featured: false,
  },
  {
    id: 'hero',
    label: 'Hero',
    amount: 100,
    frequency: 'monthly',
    description: 'Become a named sponsor of a dedicated conservation zone in Africa.',
    perks: ['All Champion perks', 'Annual field call with a conservationist', 'Named sponsorship of a conservation unit', 'VIP annual report'],
    featured: false,
  },
]

export const MEMBERSHIP_TIERS: MembershipTier[] = [
  {
    id: 'community',
    label: 'Community Member',
    description: 'Raise awareness and support Earth Protect\'s mission through your network. No minimum commitment required.',
    commitment: 'No minimum',
    perks: ['Monthly digest newsletter', 'Access to community forum', 'Digital Earth Protect badge', 'Exclusive online events'],
    applicationRequired: false,
  },
  {
    id: 'volunteer',
    label: 'Field Volunteer',
    description: 'Join ground-level conservation projects across Africa. Work alongside rangers, researchers, and local communities.',
    commitment: '1 week minimum on-site',
    perks: ['All Community perks', 'Training & safety materials', 'Travel grant consideration', 'Reference letter', 'Volunteer certification'],
    applicationRequired: true,
  },
  {
    id: 'ambassador',
    label: 'Brand Ambassador',
    description: 'Represent Earth Protect in your region. Build partnerships, run fundraising events, and grow our mission.',
    commitment: '5 hours/month minimum',
    perks: ['All Community perks', 'Official Earth Protect Ambassador kit', 'Speaking & media opportunities', 'Revenue sharing on referrals (5%)', 'Direct line to leadership team'],
    applicationRequired: true,
  },
]

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'tee-elephant',
    slug: 'elephant-guardian-tee',
    name: 'Elephant Guardian T-Shirt',
    description: 'Premium organic cotton tee featuring a hand-illustrated African elephant design. Wear your support for the gentle giants of Africa.',
    price: 35,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    category: 'apparel',
    tags: ['elephant', 'clothing', 'organic'],
    inStock: true,
    proceedsNote: '50% of proceeds directly fund elephant conservation in Kenya.',
  },
  {
    id: 'print-big-five',
    slug: 'big-five-art-print',
    name: 'Big Five Art Print Set',
    description: 'A stunning set of 5 A3 giclée prints featuring the iconic Big Five: lion, leopard, elephant, buffalo, and rhino. Museum-quality archival ink.',
    price: 65,
    imageUrl: 'https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?w=600&q=80',
    category: 'prints',
    tags: ['art', 'big five', 'print', 'gift'],
    inStock: true,
    proceedsNote: '60% of proceeds support Big Five habitat conservation.',
  },
  {
    id: 'tote-pangolin',
    slug: 'pangolin-tote-bag',
    name: 'Pangolin Tote Bag',
    description: 'Durable, reusable canvas tote bag with an adorable pangolin illustration. Say no to plastic and say yes to pangolin protection.',
    price: 22,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    category: 'accessories',
    tags: ['pangolin', 'bag', 'eco-friendly'],
    inStock: true,
    proceedsNote: '100% of proceeds help fight pangolin trafficking.',
  },
  {
    id: 'hoodie-lion',
    slug: 'lion-mane-hoodie',
    name: 'Lion Mane Hoodie',
    description: 'Cozy premium hoodie with a majestic lion illustration. Available in earthy savannah tones. Made from recycled materials.',
    price: 75,
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80',
    category: 'apparel',
    tags: ['lion', 'clothing', 'recycled'],
    inStock: true,
    proceedsNote: '40% of proceeds support lion conservation across Africa.',
  },
  {
    id: 'mug-rhino',
    slug: 'rhino-conservation-mug',
    name: 'Rhino Conservation Mug',
    description: 'Start your day knowing you\'re making a difference. This 350ml ceramic mug features a bold black rhino design with conservation facts.',
    price: 18,
    imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'accessories',
    tags: ['rhino', 'mug', 'gift'],
    inStock: true,
    proceedsNote: '70% of proceeds directly fund black rhino anti-poaching units.',
  },
  {
    id: 'pin-cheetah',
    slug: 'cheetah-enamel-pin',
    name: 'Cheetah Enamel Pin',
    description: 'Hand-crafted hard enamel pin featuring a running cheetah. Perfect for bags, jackets, and lapels. Gold plating, 3cm.',
    price: 12,
    imageUrl: 'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?w=600&q=80',
    category: 'accessories',
    tags: ['cheetah', 'pin', 'collectible'],
    inStock: true,
    proceedsNote: '80% of proceeds support cheetah habitat protection in Tanzania.',
  },
  {
    id: 'wallpaper-pack',
    slug: 'african-wildlife-wallpaper-pack',
    name: 'African Wildlife Digital Wallpaper Pack',
    description: 'A collection of 20 stunning high-resolution wildlife photographs for desktop and mobile. Includes elephant, lion, leopard, gorilla, and more.',
    price: 8,
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600&q=80',
    category: 'digital',
    tags: ['digital', 'wallpaper', 'photography'],
    inStock: true,
    proceedsNote: '100% of proceeds support wildlife photography and conservation awareness.',
  },
  {
    id: 'cap-wilddog',
    slug: 'wild-dog-cap',
    name: 'Painted Wolf Cap',
    description: 'Embroidered cap with the distinctive spotted pattern of the African wild dog. Adjustable strap, one size fits all.',
    price: 28,
    imageUrl: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&q=80',
    category: 'apparel',
    tags: ['wild dog', 'cap', 'clothing'],
    inStock: true,
    proceedsNote: '60% of proceeds fund African wild dog pack conservation.',
  },
  {
    id: 'print-gorilla',
    slug: 'mountain-gorilla-portrait',
    name: 'Mountain Gorilla Portrait Print',
    description: 'A striking A2 photographic portrait of a mountain gorilla, printed on premium archival paper. Certificate of conservation contribution included.',
    price: 45,
    imageUrl: 'https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=600&q=80',
    category: 'prints',
    tags: ['gorilla', 'print', 'photograph', 'gift'],
    inStock: true,
    proceedsNote: '75% of proceeds go directly to mountain gorilla habitat protection in the Virungas.',
  },
  {
    id: 'tee-penguin',
    slug: 'african-penguin-tee',
    name: 'African Penguin T-Shirt',
    description: 'Lightweight, breathable tee featuring a cute African penguin illustration. A playful reminder that Africa\'s wildlife extends to its coastlines.',
    price: 30,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    category: 'apparel',
    tags: ['penguin', 'clothing', 'coastal'],
    inStock: true,
    proceedsNote: '50% of proceeds support African penguin colony protection.',
  },
]

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'serengeti-wildebeest-migration-2024',
    title: 'The Great Wildebeest Migration: 2024 Season Update',
    excerpt: 'Over 1.5 million wildebeest have begun their annual journey across the Serengeti. This year\'s migration shows encouraging signs for the ecosystem\'s health.',
    content: '',
    author: 'Dr. Amara Osei',
    publishedAt: '2024-07-15',
    tags: ['migration', 'wildebeest', 'Serengeti', 'Tanzania'],
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
    category: 'news',
  },
  {
    slug: 'black-rhino-population-milestone',
    title: 'Black Rhino Numbers Cross 6,000 — A Conservation Milestone',
    excerpt: 'For the first time in decades, the black rhino population has exceeded 6,000 individuals, marking a major victory for conservation efforts across southern Africa.',
    content: '',
    author: 'Sarah Kimani',
    publishedAt: '2024-06-28',
    tags: ['rhino', 'conservation', 'southern Africa', 'milestone'],
    imageUrl: 'https://images.unsplash.com/photo-1598885159317-6c7f752e4f61?w=800&q=80',
    category: 'story',
  },
  {
    slug: 'mountain-gorilla-census-results',
    title: 'Mountain Gorilla Census: Population Climbs to 1,063',
    excerpt: 'The latest census confirms a growing mountain gorilla population — a testament to decades of international conservation effort and community engagement in the Virunga landscape.',
    content: '',
    author: 'Jean-Paul Habimana',
    publishedAt: '2024-06-10',
    tags: ['gorilla', 'census', 'Virunga', 'Rwanda'],
    imageUrl: 'https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=800&q=80',
    category: 'research',
  },
  {
    slug: 'pangolin-trafficking-crackdown',
    title: 'Major Pangolin Trafficking Network Dismantled in Central Africa',
    excerpt: 'A joint operation between rangers and international law enforcement has dismantled a major pangolin trafficking network, rescuing 47 live pangolins.',
    content: '',
    author: 'Emmanuel Diallo',
    publishedAt: '2024-05-22',
    tags: ['pangolin', 'trafficking', 'law enforcement', 'rescue'],
    imageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=800&q=80',
    category: 'news',
  },
  {
    slug: 'community-conservation-west-africa',
    title: 'How Local Communities Are Leading Conservation in West Africa',
    excerpt: 'Grassroots conservation initiatives led by local communities are proving more effective than top-down approaches in protecting wildlife corridors in Nigeria and Ghana.',
    content: '',
    author: 'Fatima Al-Hassan',
    publishedAt: '2024-05-05',
    tags: ['community', 'West Africa', 'conservation', 'Nigeria', 'Ghana'],
    imageUrl: 'https://images.unsplash.com/photo-1504892716950-5f26b0434ad8?w=800&q=80',
    category: 'story',
  },
  {
    slug: 'cheetah-gps-tracking-program',
    title: 'New GPS Tracking Program Reveals Cheetah Migration Patterns',
    excerpt: 'A new GPS collar program tracking 28 cheetahs across Tanzania and Kenya has revealed previously unknown migration corridors, informing urgent habitat protection efforts.',
    content: '',
    author: 'Dr. Lena Müller',
    publishedAt: '2024-04-18',
    tags: ['cheetah', 'GPS', 'research', 'habitat'],
    imageUrl: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80',
    category: 'research',
  },
]
